### ISSUE TITLE
Don't require defining of <img> in <a-assets>

### ISSUE THREAD

**Issue by ngokevin** [oscarmarinmiro/aframe-video-controls#10]
Need to require a couple of images requires an extra step of downloading + including.

We should have it default to a URL hosted on a CDN, but if the image with those IDs are defined, then use that `src` instead.

**Comment by oscarmarinmiro** [comment]
Thanks for pointing that out. Any recommended CDN service in your experience? Cloudflare?

**Comment by ngokevin** [comment]
Cloudflare works, or perhaps imgur?

**Comment by oscarmarinmiro** [comment]
Finally used Cloudinary. Way better now :)
