### ISSUE TITLE
Allow minor customization of the UI.

### ISSUE THREAD

**Issue by ngokevin** [oscarmarinmiro/aframe-video-controls#7]
Great component! This will be useful for many people. I am going to feature it in the A-Frame 360 Video Boilerplate.

Would like to be able to customize things like font, help text, loaded text, font-color.

Like `<a-entity video-controls="src: #video; helpText: Click play!; loadedText: ; textColor: #333; textFont: monospace>"`

**Comment by oscarmarinmiro** [comment]
Thanks @ngokevin! Sure, will do on the weekend

**Comment by ngokevin** [comment]
Done, thanks!
